# fly.toml app configuration file generated for hayati on 2023-06-27T15:33:43+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hayati"
primary_region = "sin"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
